module.exports = {
	// Nulis: require('./utils/nulis'),
	Vokal: require('./utils/vokal'),
	Base: require('./utils/base'),
	Searchnabi: require('./utils/kisahnabi'),
    Gempa: require('./utils/gempa'),
	getUser: require('./utils/igstalk'),
	ytPlay: require('./utils/ytdl'),
	jadwaltv: require('./utils/jadwaltv'),
	mfireRes: require('./utils/mediafire'),
	ytmp3: require('./utils/ytmp3'),
	ytmp4: require('./utils/ytmp4'),
	ytSearch: require('./utils/yts'),
	heroDetail: require('./utils/heroml'),
	heroList: require('./utils/herolist'),
	zodiac: require('./utils/zodiac'),
	tiktokNoWm: require('./utils/tiktoknowm'),
	xsearch: require('./utils/xnxxsearch'),
	xdetail: require('./utils/xnxxdetail'),
	chordRes: require('./utils/chord'),
	newsRes: require('./utils/news'),
	wikiRes: require('./utils/wiki'),
	lirikRes: require('./utils/lirik'),
	ucapanRes: require('./utils/ucapan'),
	kbbi: require('./utils/kbbi'),
	igdl: require('./utils/igdl'),
	igreels: require('./utils/igreels'),
	pinterest: require('./utils/pinterest'),
	playstore: require('./utils/playstore'),
	igstory: require('./utils/igstory'),
	fbdown: require('./utils/fbdl'),
	twtdl: require('./utils/twitter'),
	shoope: require('./utils/shoope')
}
